"""Added script_path to command

Revision ID: 14c4f04c9ba6
Revises: 5ef0db836fdb
Create Date: 2026-08-19 00:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '14c4f04c9ba6'
down_revision: str | Sequence[str] | None = '5ef0db836fdb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command', schema=None) as batch_op:
        batch_op.add_column(sa.Column('script_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command', schema=None) as batch_op:
        batch_op.drop_column('script_path')

    # ### end Alembic commands ###
