"""Added headers to command

Revision ID: 5ef0db836fdb
Revises: a159704d7a98
Create Date: 2026-03-31 13:43:46.276354

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5ef0db836fdb'
down_revision: str | Sequence[str] | None = 'a159704d7a98'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headers', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command', schema=None) as batch_op:
        batch_op.drop_column('headers')

    # ### end Alembic commands ###
