"""Added integration_action and integration_entity to Command

Revision ID: 730b1394d106
Revises: 5df52867947d
Create Date: 2025-09-21 15:19:01.242015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '730b1394d106'
down_revision: Union[str, Sequence[str], None] = '5df52867947d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('IR', 'BLUETOOTH', 'NETWORK', 'SCRIPT', 'INTEGRATION', name='commandtype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('IR', 'BLUETOOTH', 'NETWORK', 'SCRIPT', 'INTEGRATION', name='commandtype'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    # ### end Alembic commands ###
