"""Added integrations to command

Revision ID: a159704d7a98
Revises: 5df52867947d
Create Date: 2025-09-21 16:25:39.063758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a159704d7a98'
down_revision: Union[str, Sequence[str], None] = '5df52867947d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command', schema=None) as batch_op:
        batch_op.add_column(sa.Column('integration_action', sa.Enum('TOGGLE_LIGHT', 'BRIGHTNESS_UP', 'BRIGHTNESS_DOWN', name='integrationaction'), nullable=True))
        batch_op.add_column(sa.Column('integration_entity', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('IR', 'BLUETOOTH', 'NETWORK', 'SCRIPT', 'INTEGRATION', name='commandtype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('IR', 'BLUETOOTH', 'NETWORK', 'SCRIPT', 'INTEGRATION', name='commandtype'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
        batch_op.drop_column('integration_entity')
        batch_op.drop_column('integration_action')

    # ### end Alembic commands ###
